"""Persistenzschicht.
Lokal: SQLite (data/capa.db). Cloud: Postgres (z. B. Supabase), aktiviert über die
Umgebungsvariable bzw. das Root-Secret DATABASE_URL. Die übrige App merkt keinen Unterschied."""
from __future__ import annotations

import base64
import datetime as dt
import difflib
import os
import random
import re
import sqlite3
import threading
from contextlib import contextmanager

import pandas as pd

import logic

DB_PATH = os.environ.get(
    "CAPA_DB_PATH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "capa.db")
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS consultants(
  id {PK},
  name TEXT NOT NULL UNIQUE,
  kuerzel TEXT,
  vollname TEXT,
  rolle TEXT,
  sort INTEGER DEFAULT 0,
  aktiv INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS clients(
  id {PK},
  name TEXT NOT NULL UNIQUE,
  domain TEXT,
  aliases TEXT DEFAULT '',
  logo TEXT,
  aktiv INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS projects(
  id {PK},
  client_id INTEGER NOT NULL REFERENCES clients(id),
  name TEXT NOT NULL,
  budget_tage REAL DEFAULT 0,
  start TEXT,
  ende TEXT,
  aktiv INTEGER DEFAULT 1,
  UNIQUE(client_id, name));
CREATE TABLE IF NOT EXISTS bookings(
  consultant_id INTEGER NOT NULL REFERENCES consultants(id),
  tag TEXT NOT NULL,
  art TEXT NOT NULL,
  project_id INTEGER REFERENCES projects(id),
  notiz TEXT,
  updated_by TEXT,
  updated_at TEXT,
  PRIMARY KEY(consultant_id, tag));
CREATE INDEX IF NOT EXISTS ix_bookings_tag ON bookings(tag);
CREATE INDEX IF NOT EXISTS ix_bookings_project ON bookings(project_id);
CREATE TABLE IF NOT EXISTS entries(
  id {PK},
  consultant_id INTEGER NOT NULL REFERENCES consultants(id),
  tag TEXT NOT NULL,
  slot TEXT NOT NULL,
  art TEXT NOT NULL,
  project_id INTEGER REFERENCES projects(id),
  stunden REAL NOT NULL DEFAULT 8,
  notiz TEXT,
  updated_by TEXT,
  updated_at TEXT,
  UNIQUE(consultant_id, tag, slot));
CREATE INDEX IF NOT EXISTS ix_entries_tag ON entries(tag);
CREATE INDEX IF NOT EXISTS ix_entries_project ON entries(project_id);
CREATE TABLE IF NOT EXISTS project_members(
  project_id INTEGER NOT NULL REFERENCES projects(id),
  consultant_id INTEGER NOT NULL REFERENCES consultants(id),
  budget_tage REAL DEFAULT 0,
  PRIMARY KEY(project_id, consultant_id))
"""
PK = {"sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
      "pg": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"}


def db_url() -> str:
    return os.environ.get("DATABASE_URL", "").strip()


def is_pg() -> bool:
    return db_url().startswith(("postgres://", "postgresql://"))


def backend() -> str:
    return "Postgres" if is_pg() else "SQLite (lokal)"


class _Conn:
    """Dünner Adapter: einheitliche ?-Platzhalter und Dict-Zeilen für beide Backends."""

    def __init__(self, raw, pg: bool):
        self.raw, self.pg = raw, pg

    def _q(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.pg else sql

    def execute(self, sql: str, params=()):
        if self.pg:
            cur = self.raw.cursor()
            cur.execute(self._q(sql), params)
            return cur
        return self.raw.execute(sql, params)

    def executemany(self, sql: str, seq):
        seq = list(seq)
        if not seq:
            return None
        if self.pg:
            cur = self.raw.cursor()
            cur.executemany(self._q(sql), seq)
            return cur
        return self.raw.executemany(sql, seq)

    def insert_id(self, sql: str, params=()) -> int:
        return self.execute(sql + " RETURNING id", params).fetchone()["id"]

    def script(self, sql: str) -> None:
        for stmt in (x.strip() for x in sql.split(";")):
            if stmt:
                self.execute(stmt)


_pool = None
_pool_lock = threading.Lock()


def _get_pool():
    global _pool
    with _pool_lock:
        if _pool is None:
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool
            # prepare_threshold=None: kompatibel mit Supabase Pooler
            _pool = ConnectionPool(db_url(), min_size=1, max_size=5, open=True, timeout=20,
                                   kwargs={"row_factory": dict_row, "prepare_threshold": None,
                                           "connect_timeout": 10})
        return _pool


@contextmanager
def connect():
    if is_pg():
        with _get_pool().connection() as raw:  # Commit bei Erfolg, Rollback bei Fehler
            yield _Conn(raw, True)
        return
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    con = sqlite3.connect(DB_PATH, timeout=15)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA foreign_keys=ON")
    try:
        yield _Conn(con, False)
        con.commit()
    finally:
        con.close()


def _df(sql: str, params=()) -> pd.DataFrame:
    with connect() as con:
        cur = con.execute(sql, params)
        rows = cur.fetchall()
        cols = [d[0] for d in cur.description]
    return pd.DataFrame([tuple(r.values()) if isinstance(r, dict) else tuple(r) for r in rows], columns=cols)


def _now() -> str:
    return dt.datetime.now().isoformat(timespec="seconds")


def demo_enabled() -> bool:
    return os.environ.get("DEMO_DATEN", "true").strip().lower() in ("1", "true", "ja", "yes")


def _add_col(con, table: str, col: str, typ: str) -> None:
    if con.pg:
        con.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {col} {typ}")
    else:
        cols = [r["name"] for r in con.execute(f"PRAGMA table_info({table})").fetchall()]
        if col not in cols:
            con.execute(f"ALTER TABLE {table} ADD COLUMN {col} {typ}")


def _migrate(con) -> None:
    """Nachträgliche Spalten und Übernahme der alten Tagesbuchungen (8 h je Tag)."""
    _add_col(con, "consultants", "vollname", "TEXT")
    _add_col(con, "projects", "leiter_id", "INTEGER")
    n_new = con.execute("SELECT COUNT(*) AS n FROM entries").fetchone()["n"]
    n_old = con.execute("SELECT COUNT(*) AS n FROM bookings").fetchone()["n"]
    if n_new or not n_old:
        return
    con.execute("""INSERT INTO entries(consultant_id, tag, slot, art, project_id, stunden, updated_by, updated_at)
                   SELECT consultant_id, tag,
                          CASE WHEN project_id IS NULL THEN art ELSE 'p' || project_id END,
                          art, project_id, 8, updated_by, updated_at
                   FROM bookings""")
    # Budget je Berater: Projektbudget anteilig nach bisher gebuchten Tagen verteilen
    pairs = con.execute("""SELECT b.project_id AS pid, b.consultant_id AS cid, COUNT(*) AS n,
                                  COALESCE(p.budget_tage, 0) AS budget
                           FROM bookings b JOIN projects p ON p.id = b.project_id
                           WHERE b.project_id IS NOT NULL
                           GROUP BY b.project_id, b.consultant_id, p.budget_tage""").fetchall()
    total = {}
    for r in pairs:
        total[r["pid"]] = total.get(r["pid"], 0) + r["n"]
    for r in pairs:
        b = r["budget"] * r["n"] / total[r["pid"]] if r["budget"] else r["n"]
        con.execute("INSERT INTO project_members(project_id, consultant_id, budget_tage) VALUES(?,?,?) "
                    "ON CONFLICT(project_id, consultant_id) DO NOTHING", (r["pid"], r["cid"], round(b * 2) / 2))


def init_db(seed: bool | None = None, team: list[str] | None = None) -> None:
    """team: Kürzel des echten Teams; werden beim allerersten Start angelegt."""
    seed = demo_enabled() if seed is None else seed
    with connect() as con:
        con.script(SCHEMA.replace("{PK}", PK["pg" if con.pg else "sqlite"]))
        _migrate(con)
        empty = con.execute("SELECT COUNT(*) AS n FROM consultants").fetchone()["n"] == 0
    if not empty:
        return
    if seed:
        seed_demo(team)
    elif team:
        for k in team:
            create_consultant(k)


# ---------------------------------------------------------------- Lesen
def consultants(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE aktiv=1" if active_only else ""
    return _df(f"SELECT * FROM consultants {where} ORDER BY sort, name")


def clients(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE aktiv=1" if active_only else ""
    return _df(f"SELECT * FROM clients {where} ORDER BY LOWER(name)")


def projects(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE p.aktiv=1 AND c.aktiv=1" if active_only else ""
    df = _df(
        f"""SELECT p.*, c.name AS kunde, c.domain, c.logo
            FROM projects p JOIN clients c ON c.id=p.client_id {where}
            ORDER BY LOWER(c.name), p.name""")
    df["label"] = [k if n == k else f"{k} | {n}" for k, n in zip(df["kunde"], df["name"])]
    for col in ("start", "ende"):
        df[col] = pd.to_datetime(df[col], errors="coerce").dt.date
    return df


def entries(start: dt.date | None = None, end: dt.date | None = None, consultant_id: int | None = None,
            project_id: int | None = None, project_only: bool = False) -> pd.DataFrame:
    """Planungseinträge (mehrere je Tag möglich, in Stunden)."""
    cond, params = [], []
    if start:
        cond.append("e.tag >= ?"); params.append(start.isoformat())
    if end:
        cond.append("e.tag <= ?"); params.append(end.isoformat())
    if consultant_id is not None:
        cond.append("e.consultant_id = ?"); params.append(int(consultant_id))
    if project_id is not None:
        cond.append("e.project_id = ?"); params.append(int(project_id))
    if project_only:
        cond.append("e.project_id IS NOT NULL")
    where = ("WHERE " + " AND ".join(cond)) if cond else ""
    df = _df(f"""SELECT e.*, k.name FROM entries e
                 JOIN consultants k ON k.id = e.consultant_id {where}""", params)
    df["tag"] = pd.to_datetime(df["tag"]).dt.date
    df["stunden"] = pd.to_numeric(df["stunden"]).astype(float)
    return df


bookings = entries  # Rückwärtskompatibilität


def members(project_id: int | None = None) -> pd.DataFrame:
    where, params = ("WHERE m.project_id = ?", (int(project_id),)) if project_id is not None else ("", ())
    df = _df(f"""SELECT m.project_id, m.consultant_id, m.budget_tage, k.name
                 FROM project_members m JOIN consultants k ON k.id = m.consultant_id {where}""", params)
    df["budget_tage"] = pd.to_numeric(df["budget_tage"]).fillna(0).astype(float)
    return df


def recent_changes(n: int = 15) -> pd.DataFrame:
    return _df("""SELECT e.updated_at AS zeitpunkt, e.updated_by AS von, k.name AS berater,
                         e.tag, e.art, e.stunden, c.name AS kunde
                  FROM entries e JOIN consultants k ON k.id = e.consultant_id
                  LEFT JOIN projects p ON p.id = e.project_id
                  LEFT JOIN clients c ON c.id = p.client_id
                  ORDER BY e.updated_at DESC NULLS LAST LIMIT ?""", (n,))


# ---------------------------------------------------------------- Schreiben: Einträge
def _slot(art: str, project_id) -> str:
    return f"p{int(project_id)}" if project_id is not None and art in logic.PROJEKT_ARTEN else art


def upsert_entries(rows: list[tuple], user: str) -> int:
    """rows: (consultant_id, tag, art, project_id | None, stunden). Gleiches Projekt am gleichen Tag
    wird aktualisiert (Ort, Stunden), andere Einträge des Tages bleiben bestehen."""
    ts = _now()
    data = [(int(c), t.isoformat(), _slot(a, p), a, None if p is None else int(p), float(h), user, ts)
            for c, t, a, p, h in rows]
    with connect() as con:
        con.executemany(
            """INSERT INTO entries(consultant_id, tag, slot, art, project_id, stunden, updated_by, updated_at)
               VALUES(?,?,?,?,?,?,?,?)
               ON CONFLICT(consultant_id, tag, slot) DO UPDATE SET
                 art=excluded.art, project_id=excluded.project_id, stunden=excluded.stunden,
                 updated_by=excluded.updated_by, updated_at=excluded.updated_at""", data)
    return len(data)


def set_week_target(cid: int, ws: dt.date, art: str, project_id, target_days: float, ort: str, user: str,
                    min_day: dt.date | None = None) -> int:
    """Setzt für eine Person und Woche die Tage eines Projekts bzw. einer Abwesenheit auf einen Zielwert.
    Verteilt auf freie Arbeitstage (Feiertage ausgenommen), baut bei Reduktion von Freitag her ab.
    min_day: nur Tage ab diesem Datum verändern (z. B. beim Verteilen ab heute)."""
    days = [ws + dt.timedelta(days=i) for i in range(5)]
    days = [d for d in days if not logic.feiertag_name(d) and (min_day is None or d >= min_day)]
    if not days:
        return 0
    slot = _slot(art, project_id) if project_id is None else f"p{int(project_id)}"
    e = entries(days[0], days[-1], consultant_id=cid)
    mine = e[e["slot"] == slot] if not e.empty else e
    other = e[e["slot"] != slot] if not e.empty else e
    m = mine.groupby("tag")["stunden"].sum().to_dict() if not mine.empty else {}
    o = other.groupby("tag")["stunden"].sum().to_dict() if not other.empty else {}
    arts = dict(zip(mine["tag"], mine["art"])) if not mine.empty else {}
    plan = logic.week_fill_plan(float(target_days) * logic.TAG_H, m, o, days)
    ups, dels = [], []
    for d, h in plan.items():
        if h <= 1e-9:
            dels.append((int(cid), d.isoformat(), slot))
        else:
            a = arts.get(d, ort if project_id is not None else art)
            ups.append((cid, d, a, project_id, h))
    if ups:
        upsert_entries(ups, user)
    if dels:
        with connect() as con:
            con.executemany("DELETE FROM entries WHERE consultant_id=? AND tag=? AND slot=?", dels)
    return len(plan)


def distribute_open(cid: int, project_id: int, tage: float, ab: dt.date, pro_woche: float, ort: str,
                    user: str, dry_run: bool = False) -> list[tuple[dt.date, float]]:
    """Verteilt offene Beratertage ab einer Woche mit x Tagen pro Woche. Rückgabe: [(montag, tage_neu_gesamt)]."""
    plan, rest, ws = [], float(tage), logic.monday(ab)
    e = entries(ab, ws + dt.timedelta(weeks=60), consultant_id=cid, project_id=project_id)
    cur = e.groupby(e["tag"].map(logic.monday))["stunden"].sum().to_dict() if not e.empty else {}
    for _ in range(60):
        if rest <= 1e-9:
            break
        cap = len([1 for i in range(5) if not logic.feiertag_name(ws + dt.timedelta(days=i))
                   and ws + dt.timedelta(days=i) >= ab])
        have = cur.get(ws, 0.0) / logic.TAG_H   # nur Tage ab 'ab' zählen
        put = min(max(min(pro_woche, cap) - have, 0.0), rest)
        if put > 1e-9:
            plan.append((ws, have, put))
            rest -= put
        ws += dt.timedelta(weeks=1)
    if not dry_run:
        for w, have, put in plan:
            set_week_target(cid, w, ort, project_id, have + put, ort, user, min_day=ab)
    return plan


def set_ort(cid: int, project_id: int, start: dt.date, end: dt.date, ort: str, user: str) -> int:
    """Stellt alle Tage eines Projekts im Zeitraum auf Vor Ort bzw. Remote um."""
    with connect() as con:
        return con.execute("UPDATE entries SET art=?, updated_by=?, updated_at=? WHERE consultant_id=? AND "
                           "project_id=? AND tag BETWEEN ? AND ? AND art<>?",
                           (ort, user, _now(), int(cid), int(project_id), start.isoformat(), end.isoformat(),
                            ort)).rowcount


def update_project_core(project_id: int, client_id: int, name: str, budget: float | None) -> None:
    with connect() as con:
        con.execute("UPDATE projects SET client_id=?, name=?, budget_tage=? WHERE id=?",
                    (int(client_id), name.strip(), float(budget or 0), int(project_id)))


def update_client(client_id: int, name: str | None = None, domain: str | None = None) -> None:
    with connect() as con:
        if name:
            con.execute("UPDATE clients SET name=? WHERE id=?", (name.strip(), int(client_id)))
        if domain is not None:
            con.execute("UPDATE clients SET domain=? WHERE id=?", (domain.strip(), int(client_id)))


def import_startdaten(team: list[dict], projekte: list[dict], budgets: list[dict], planung: list[dict],
                      user: str, replace: bool = True) -> dict:
    """Übernimmt Startdaten (Team, Projekte, Budgets, Tageseinträge). replace=True löscht vorher alle
    Planungsdaten inkl. Testdaten; Mitarbeiter, die nicht im Team stehen, werden deaktiviert."""
    if replace:
        reset_planning()
    kz_ids = {}
    for i, t in enumerate(team):
        cid_, _ = create_consultant(t["kuerzel"], t.get("name") or "", t.get("rolle") or "")
        with connect() as con:
            con.execute("UPDATE consultants SET sort=? WHERE id=?", (i, cid_))
        kz_ids[t["kuerzel"].lower()] = cid_
    if replace and kz_ids:
        with connect() as con:
            for r in con.execute("SELECT id, name FROM consultants").fetchall():
                if r["name"].lower() not in kz_ids:
                    con.execute("UPDATE consultants SET aktiv=0 WHERE id=?", (r["id"],))
    allc = consultants(active_only=False)
    kz_ids.update({str(n).lower(): int(i) for n, i in zip(allc["name"], allc["id"])})
    clients_ = {}
    pids = {}
    for p in projekte:
        k = p["kunde"].strip()
        if k not in clients_:
            hit = match_client(k)
            clients_[k] = int(hit["id"]) if hit is not None and hit["name"] == k else create_client(k, p.get("website") or "")
        pid = ensure_project(clients_[k], p["projekt"])
        lid = kz_ids.get(str(p.get("leitung") or "").lower())
        update_project_meta(pid, start=p.get("start"), ende=p.get("ende"), leiter_id=lid, aktiv=True)
        with connect() as con:
            con.execute("UPDATE projects SET budget_tage=? WHERE id=?", (float(p.get("budget") or 0), pid))
        pids[(k, p["projekt"].strip())] = pid
    for b in budgets:
        pid = pids.get((b["kunde"].strip(), b["projekt"].strip()))
        cid_ = kz_ids.get(b["kuerzel"].lower())
        if pid and cid_:
            with connect() as con:
                con.execute("INSERT INTO project_members(project_id, consultant_id, budget_tage) VALUES(?,?,?) "
                            "ON CONFLICT(project_id, consultant_id) DO UPDATE SET budget_tage=excluded.budget_tage",
                            (pid, cid_, float(b["budget"] or 0)))
    rows, skipped = [], 0
    for e in planung:
        cid_ = kz_ids.get(e["kuerzel"].lower())
        pid = pids.get(((e.get("kunde") or "").strip(), (e.get("projekt") or "").strip())) if e.get("kunde") else None
        if not cid_ or (e.get("kunde") and not pid):
            skipped += 1
            continue
        rows.append((cid_, e["datum"], e["art"], pid, float(e["stunden"])))
    # gleiche Person/Tag/Slot zusammenfassen
    agg = {}
    for c, d, a, p, h in rows:
        k_ = (c, d, _slot(a, p))
        agg[k_] = (c, d, a, p, agg.get(k_, (0, 0, 0, 0, 0))[4] + h)
    upsert_entries(list(agg.values()), user)
    return {"team": len(team), "projekte": len(pids), "budgets": len(budgets), "eintraege": len(agg),
            "uebersprungen": skipped}


def delete_entry(entry_id: int) -> None:
    with connect() as con:
        con.execute("DELETE FROM entries WHERE id = ?", (int(entry_id),))


def delete_slots(consultant_id: int, items: list[tuple[dt.date, str]]) -> int:
    """Einzelne Einträge löschen: (tag, slot) mit slot = 'p{project_id}' oder Art (Urlaub, Intern ...)."""
    with connect() as con:
        n = 0
        for d, slot in items:
            n += con.execute("DELETE FROM entries WHERE consultant_id = ? AND tag = ? AND slot = ?",
                             (int(consultant_id), d.isoformat(), slot)).rowcount
        return n


def clear_days(consultant_id: int, days: list[dt.date]) -> int:
    with connect() as con:
        n = 0
        for d in days:
            n += con.execute("DELETE FROM entries WHERE consultant_id = ? AND tag = ?",
                             (int(consultant_id), d.isoformat())).rowcount
        return n


def clear_range(consultant_ids, start: dt.date, end: dt.date) -> int:
    with connect() as con:
        n = 0
        for c in consultant_ids:
            n += con.execute("DELETE FROM entries WHERE consultant_id = ? AND tag BETWEEN ? AND ?",
                             (int(c), start.isoformat(), end.isoformat())).rowcount
        return n


def set_members(project_id: int, rows: list[tuple[int, float]]) -> None:
    """Team und Budget (Beratertage) eines Projekts komplett setzen."""
    with connect() as con:
        con.execute("DELETE FROM project_members WHERE project_id = ?", (int(project_id),))
        con.executemany("INSERT INTO project_members(project_id, consultant_id, budget_tage) VALUES(?,?,?)",
                        [(int(project_id), int(c), float(b or 0)) for c, b in rows])


def add_member(project_id: int, consultant_id: int) -> None:
    with connect() as con:
        con.execute("INSERT INTO project_members(project_id, consultant_id, budget_tage) VALUES(?,?,0) "
                    "ON CONFLICT(project_id, consultant_id) DO NOTHING", (int(project_id), int(consultant_id)))


# ---------------------------------------------------------------- Kundenerkennung & Logos
_RECHTSFORMEN = r"\b(gmbh|ag|se|kg|kgaa|co|mbh|holding|group|gruppe|international|deutschland)\b"
_UML = str.maketrans({"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"})


def _norm(s: str) -> str:
    s = (s or "").lower().translate(_UML)
    s = re.sub(_RECHTSFORMEN, " ", s)
    return re.sub(r"[^a-z0-9]", "", s)


def match_client(name: str, cutoff: float = 0.8):
    """Erkennt bestehende Kunden trotz Tippfehlern, Rechtsform oder Alias.
    Rückgabe: Zeile (pd.Series) oder None."""
    df = clients(active_only=False)
    n = _norm(name)
    if not n or df.empty:
        return None
    keys: dict[str, int] = {}
    for r in df.itertuples():
        for k in [r.name] + [a for a in (r.aliases or "").split(",") if a.strip()]:
            keys[_norm(k)] = r.id
    hit = keys.get(n)
    if hit is None and len(n) >= 4:
        hit = next((cid for k, cid in keys.items() if len(k) >= 4 and (n in k or k in n)), None)
    if hit is None:
        m = difflib.get_close_matches(n, list(keys), n=1, cutoff=cutoff)
        hit = keys[m[0]] if m else None
    return None if hit is None else df[df["id"] == hit].iloc[0]


def guess_domain(name: str) -> str:
    return f"{_norm(name)}.de" if _norm(name) else ""


def initials_svg(name: str, bg: str = "#6688BB") -> str:
    words = re.findall(r"[A-Za-zÄÖÜäöü0-9]+", name or "?")
    ini = "".join(w[0] for w in words[:2]).upper() or "?"
    svg = (f"<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'>"
           f"<rect width='64' height='64' rx='12' fill='{bg}'/>"
           f"<text x='50%' y='54%' dominant-baseline='middle' text-anchor='middle' "
           f"font-family='Calibri,Arial' font-size='26' font-weight='700' fill='#fff'>{ini}</text></svg>")
    return "data:image/svg+xml;base64," + base64.b64encode(svg.encode()).decode()


def logo_src(name: str, domain: str | None, logo: str | None, token: str | None = None) -> str:
    """Priorität: hochgeladenes Logo > logo.dev (Token) > Favicon-Dienst > Initialen."""
    if isinstance(logo, str) and logo:
        return logo
    if isinstance(domain, str) and domain.strip():
        d = domain.strip().replace("https://", "").replace("http://", "").strip("/")
        if token:
            return f"https://img.logo.dev/{d}?token={token}&size=64&format=png"
        return f"https://www.google.com/s2/favicons?domain={d}&sz=64"
    return initials_svg(name)


def create_client(name: str, domain: str | None = None, aliases: str = "") -> int:
    with connect() as con:
        return con.insert_id("INSERT INTO clients(name, domain, aliases) VALUES(?,?,?)",
                             (name.strip(), (domain or guess_domain(name)).strip(), (aliases or "").strip()))


def ensure_project(client_id: int, name: str) -> int:
    name = (name or "Projekt").strip()
    with connect() as con:
        row = con.execute("SELECT id FROM projects WHERE client_id=? AND name=?", (client_id, name)).fetchone()
        if row:
            return row["id"]
        return con.insert_id("INSERT INTO projects(client_id, name) VALUES(?,?)", (client_id, name))


def _pnorm(s: str) -> list[str]:
    """Personennamen normalisieren: Kleinschrift, Umlaute, Satzzeichen weg, Reihenfolge egal."""
    s = s if isinstance(s, str) else ""
    s = s.lower().translate(_UML).replace(",", " ")
    return sorted(t for t in re.split(r"[^a-z0-9]+", s) if t)


def find_consultant(text: str):
    """Findet einen aktiven Mitarbeiter über 'Vorname Nachname', 'Nachname, Vorname' oder Kürzel."""
    q = _pnorm(text)
    if not q:
        return None
    for r in consultants().to_dict("records"):
        if q == _pnorm(r.get("name")) or q == _pnorm(r.get("vollname")):
            return r
    return None


def suggest_kuerzel(vollname: str) -> str:
    """Muster: 1. Buchstabe Vorname + 2 Buchstaben Nachname (z. B. Max Mustermann = mmu)."""
    t = [x for x in re.split(r"[^a-z]+", (vollname or "").lower().translate(_UML)) if x]
    base = (t[0][0] + t[-1][:2]) if len(t) >= 2 else (t[0][:3] if t else "neu")
    taken = {str(x).lower() for x in consultants(active_only=False)["name"]}
    k, i = base, 2
    while k in taken:
        k, i = f"{base}{i}", i + 1
    return k


def create_consultant(name: str, vollname: str = "", rolle: str = "") -> tuple[int, bool]:
    """Legt einen Mitarbeiter an oder reaktiviert ihn. Rückgabe: (id, neu_angelegt)."""
    name = name.strip()
    with connect() as con:
        row = con.execute("SELECT id FROM consultants WHERE LOWER(name)=LOWER(?)", (name,)).fetchone()
        if row:
            con.execute("UPDATE consultants SET aktiv=1, vollname=COALESCE(NULLIF(?, ''), vollname), "
                        "rolle=COALESCE(NULLIF(?, ''), rolle) WHERE id=?", (vollname, rolle, row["id"]))
            return row["id"], False
        nxt = con.execute("SELECT COALESCE(MAX(sort), -1) + 1 AS n FROM consultants").fetchone()["n"]
        return con.insert_id("INSERT INTO consultants(name, vollname, rolle, sort) VALUES(?,?,?,?)",
                             (name, vollname or None, rolle or None, nxt)), True


def update_project_meta(project_id: int, start: dt.date | None = None, ende: dt.date | None = None,
                        leiter_id: int | None = None, aktiv: bool | None = None) -> None:
    sets, params = [], []
    for col, v in (("start", start), ("ende", ende)):
        if v is not None:
            sets.append(f"{col}=?"); params.append(v.isoformat())
    if leiter_id is not None:
        sets.append("leiter_id=?"); params.append(int(leiter_id))
    if aktiv is not None:
        sets.append("aktiv=?"); params.append(1 if aktiv else 0)
    if sets:
        with connect() as con:
            con.execute(f"UPDATE projects SET {', '.join(sets)} WHERE id=?", params + [int(project_id)])


def reset_planning() -> None:
    """Löscht alle Buchungen, Projekte und Kunden. Das Team bleibt erhalten."""
    with connect() as con:
        for t in ("entries", "bookings", "project_members", "projects", "clients"):
            con.execute(f"DELETE FROM {t}")


def set_logo(client_id: int, data_uri: str | None) -> None:
    with connect() as con:
        con.execute("UPDATE clients SET logo=? WHERE id=?", (data_uri, client_id))


# ---------------------------------------------------------------- Stammdaten speichern
def _isnew(v) -> bool:
    return v is None or (isinstance(v, float) and pd.isna(v))


def save_table(table: str, cols: list[str], edited: pd.DataFrame, original: pd.DataFrame) -> None:
    """Upsert geänderter Zeilen, entfernte Zeilen werden deaktiviert (Soft Delete)."""
    def val(v):
        if isinstance(v, (dt.date, dt.datetime)):
            return v.isoformat()[:10]
        if v is None or (isinstance(v, float) and pd.isna(v)) or v is pd.NaT:
            return None
        return v.item() if hasattr(v, "item") else v

    with connect() as con:
        for _, r in edited.iterrows():
            values = [val(r.get(c)) for c in cols]
            if _isnew(r.get("id")):
                if not values[0]:
                    continue
                con.execute(f"INSERT INTO {table}({','.join(cols)}) VALUES({','.join('?' * len(cols))})", values)
            else:
                sets = ",".join(f"{c}=?" for c in cols)
                con.execute(f"UPDATE {table} SET {sets} WHERE id=?", values + [int(r['id'])])
        removed = set(original["id"].dropna().astype(int)) - set(edited["id"].dropna().astype(int))
        for rid in removed:
            con.execute(f"UPDATE {table} SET aktiv=0 WHERE id=?", (rid,))


# ---------------------------------------------------------------- Demo-Daten
def seed_demo(team_kuerzel: list[str] | None = None) -> None:
    today = dt.date.today()
    team = [("Max", "", "Senior Consultant"), ("Anna", "", "Projektleiterin"),
            ("Ben", "", "Consultant"), ("Clara", "", "Senior Consultant"),
            ("David", "", "Consultant"), ("Eva", "", "Projektleiterin"),
            ("Felix", "", "Consultant"), ("Hannah", "", "Senior Consultant"),
            ("Jonas", "", "Consultant"), ("Lena", "", "Consultant")]
    # Fiktive Demo-Kunden (keine echten Mandanten)
    kunden = [("Alpenwerk Maschinenbau", "", "Alpenwerk", "S&OP Einführung"),
              ("Isartal Chemie", "", "ITC", "Footprint Analyse"),
              ("Brennerhof Möbel", "", "BHM", "Baukasten Portfolio"),
              ("Donaumetall", "", "DM", "Szenarien Produktion"),
              ("Nordstern Logistik", "", "", "Lageroptimierung"),
              ("Bergmann Medizintechnik", "", "BMT", "OpEx Programm"),
              ("Kessler Antriebe", "", "", "Supply Chain")]
    if team_kuerzel:
        team = [(k, "", "") for k in team_kuerzel]
    rng = random.Random(42)
    with connect() as con:
        for i, (n, v, r) in enumerate(team):
            con.execute("INSERT INTO consultants(name,vollname,rolle,sort) VALUES(?,?,?,?)",
                        (n, v or None, r or None, i))
        pids = []
        for name, dom, ali, proj in kunden:
            cid = con.insert_id("INSERT INTO clients(name,domain,aliases) VALUES(?,?,?)", (name, dom, ali))
            pids.append(con.insert_id("INSERT INTO projects(client_id,name) VALUES(?,?)", (cid, proj)))
        cons = [r["id"] for r in con.execute("SELECT id FROM consultants ORDER BY id").fetchall()]

    start = logic.monday(today) - dt.timedelta(weeks=8)
    end = logic.month_end(today, 5)
    days = logic.workdays(start, end)
    rows = []
    for cid in cons:
        cur = start
        while cur < end:
            # Pipeline wird nach hinten dünner: realistische Kapazitätslücke ab ca. 8 Wochen
            if cur > today + dt.timedelta(weeks=8) and rng.random() < 0.45:
                cur += dt.timedelta(weeks=rng.randint(2, 5))
                continue
            pid = rng.choice(pids)
            stop = cur + dt.timedelta(weeks=rng.randint(4, 10))
            for d in (x for x in days if cur <= x < stop):
                if d.weekday() <= 3:
                    art = "Vor Ort" if rng.random() > 0.1 else "Remote"
                    if rng.random() < 0.12:  # geteilter Tag: 4 h hier, 4 h anderes Projekt remote
                        rows.append((cid, d, art, pid, 4.0))
                        rows.append((cid, d, "Remote", rng.choice([p for p in pids if p != pid]), 4.0))
                    else:
                        rows.append((cid, d, art, pid, 8.0))
                else:
                    art = rng.choice(["Remote", "Intern", "Remote", "Akquise"])
                    rows.append((cid, d, art, pid if art in logic.PROJEKT_ARTEN else None, 8.0))
            cur = stop
        urlaub = logic.monday(today) + dt.timedelta(weeks=rng.randint(1, 14))
        for d in (x for x in days if urlaub <= x < urlaub + dt.timedelta(days=5)):
            rows = [r for r in rows if not (r[0] == cid and r[1] == d)]
            rows.append((cid, d, "Urlaub", None, 8.0))
    upsert_entries(rows, "Demo")

    with connect() as con:
        for pid in pids:
            row = con.execute("SELECT MIN(tag) AS s, MAX(tag) AS e FROM entries WHERE project_id=?", (pid,)).fetchone()
            per = con.execute("""SELECT consultant_id AS cid, SUM(stunden) AS h FROM entries
                                 WHERE project_id=? GROUP BY consultant_id ORDER BY SUM(stunden) DESC""",
                              (pid,)).fetchall()
            for i, r in enumerate(per):
                budget = round(r["h"] / 8 * rng.uniform(0.85, 1.25) * 2) / 2
                con.execute("INSERT INTO project_members(project_id, consultant_id, budget_tage) VALUES(?,?,?)",
                            (pid, r["cid"], budget))
            con.execute("UPDATE projects SET start=?, ende=?, leiter_id=? WHERE id=?",
                        (row["s"], row["e"], per[0]["cid"] if per else None, pid))
