"""Persistenzschicht.
Lokal: SQLite (data/capa.db). Cloud: Postgres (z. B. Supabase), aktiviert über die
Umgebungsvariable bzw. das Root-Secret DATABASE_URL. Die übrige App merkt keinen Unterschied."""
from __future__ import annotations

import base64
import datetime as dt
import difflib
import os
import random
import re
import sqlite3
import threading
from contextlib import contextmanager

import pandas as pd

import logic

DB_PATH = os.environ.get(
    "CAPA_DB_PATH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "capa.db")
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS consultants(
  id {PK},
  name TEXT NOT NULL UNIQUE,
  kuerzel TEXT,
  vollname TEXT,
  rolle TEXT,
  sort INTEGER DEFAULT 0,
  aktiv INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS clients(
  id {PK},
  name TEXT NOT NULL UNIQUE,
  domain TEXT,
  aliases TEXT DEFAULT '',
  logo TEXT,
  aktiv INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS projects(
  id {PK},
  client_id INTEGER NOT NULL REFERENCES clients(id),
  name TEXT NOT NULL,
  budget_tage REAL DEFAULT 0,
  start TEXT,
  ende TEXT,
  aktiv INTEGER DEFAULT 1,
  UNIQUE(client_id, name));
CREATE TABLE IF NOT EXISTS bookings(
  consultant_id INTEGER NOT NULL REFERENCES consultants(id),
  tag TEXT NOT NULL,
  art TEXT NOT NULL,
  project_id INTEGER REFERENCES projects(id),
  notiz TEXT,
  updated_by TEXT,
  updated_at TEXT,
  PRIMARY KEY(consultant_id, tag));
CREATE INDEX IF NOT EXISTS ix_bookings_tag ON bookings(tag);
CREATE INDEX IF NOT EXISTS ix_bookings_project ON bookings(project_id)
"""
PK = {"sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
      "pg": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"}


def db_url() -> str:
    return os.environ.get("DATABASE_URL", "").strip()


def is_pg() -> bool:
    return db_url().startswith(("postgres://", "postgresql://"))


def backend() -> str:
    return "Postgres" if is_pg() else "SQLite (lokal)"


class _Conn:
    """Dünner Adapter: einheitliche ?-Platzhalter und Dict-Zeilen für beide Backends."""

    def __init__(self, raw, pg: bool):
        self.raw, self.pg = raw, pg

    def _q(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.pg else sql

    def execute(self, sql: str, params=()):
        if self.pg:
            cur = self.raw.cursor()
            cur.execute(self._q(sql), params)
            return cur
        return self.raw.execute(sql, params)

    def executemany(self, sql: str, seq):
        seq = list(seq)
        if not seq:
            return None
        if self.pg:
            cur = self.raw.cursor()
            cur.executemany(self._q(sql), seq)
            return cur
        return self.raw.executemany(sql, seq)

    def insert_id(self, sql: str, params=()) -> int:
        return self.execute(sql + " RETURNING id", params).fetchone()["id"]

    def script(self, sql: str) -> None:
        for stmt in (x.strip() for x in sql.split(";")):
            if stmt:
                self.execute(stmt)


_pool = None
_pool_lock = threading.Lock()


def _get_pool():
    global _pool
    with _pool_lock:
        if _pool is None:
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool
            # prepare_threshold=None: kompatibel mit Supabase Pooler
            _pool = ConnectionPool(db_url(), min_size=1, max_size=5, open=True, timeout=20,
                                   kwargs={"row_factory": dict_row, "prepare_threshold": None,
                                           "connect_timeout": 10})
        return _pool


@contextmanager
def connect():
    if is_pg():
        with _get_pool().connection() as raw:  # Commit bei Erfolg, Rollback bei Fehler
            yield _Conn(raw, True)
        return
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    con = sqlite3.connect(DB_PATH, timeout=15)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA foreign_keys=ON")
    try:
        yield _Conn(con, False)
        con.commit()
    finally:
        con.close()


def _df(sql: str, params=()) -> pd.DataFrame:
    with connect() as con:
        cur = con.execute(sql, params)
        rows = cur.fetchall()
        cols = [d[0] for d in cur.description]
    return pd.DataFrame([tuple(r.values()) if isinstance(r, dict) else tuple(r) for r in rows], columns=cols)


def _now() -> str:
    return dt.datetime.now().isoformat(timespec="seconds")


def demo_enabled() -> bool:
    return os.environ.get("DEMO_DATEN", "true").strip().lower() in ("1", "true", "ja", "yes")


def _migrate(con) -> None:
    """Nachträgliche Spalten für bestehende Datenbanken."""
    if con.pg:
        con.execute("ALTER TABLE consultants ADD COLUMN IF NOT EXISTS vollname TEXT")
    else:
        cols = [r["name"] for r in con.execute("PRAGMA table_info(consultants)").fetchall()]
        if "vollname" not in cols:
            con.execute("ALTER TABLE consultants ADD COLUMN vollname TEXT")


def init_db(seed: bool | None = None, team: list[str] | None = None) -> None:
    """team: Kürzel des echten Teams; werden beim allerersten Start angelegt."""
    seed = demo_enabled() if seed is None else seed
    with connect() as con:
        con.script(SCHEMA.replace("{PK}", PK["pg" if con.pg else "sqlite"]))
        _migrate(con)
        empty = con.execute("SELECT COUNT(*) AS n FROM consultants").fetchone()["n"] == 0
    if not empty:
        return
    if seed:
        seed_demo(team)
    elif team:
        for k in team:
            create_consultant(k)


# ---------------------------------------------------------------- Lesen
def consultants(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE aktiv=1" if active_only else ""
    return _df(f"SELECT * FROM consultants {where} ORDER BY sort, name")


def clients(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE aktiv=1" if active_only else ""
    return _df(f"SELECT * FROM clients {where} ORDER BY LOWER(name)")


def projects(active_only: bool = True) -> pd.DataFrame:
    where = "WHERE p.aktiv=1 AND c.aktiv=1" if active_only else ""
    df = _df(
        f"""SELECT p.*, c.name AS kunde, c.domain, c.logo
            FROM projects p JOIN clients c ON c.id=p.client_id {where}
            ORDER BY LOWER(c.name), p.name""")
    df["label"] = df["kunde"] + " | " + df["name"]
    for col in ("start", "ende"):
        df[col] = pd.to_datetime(df[col], errors="coerce").dt.date
    return df


def bookings(start: dt.date | None = None, end: dt.date | None = None,
             project_only: bool = False) -> pd.DataFrame:
    cond, params = [], []
    if start:
        cond.append("b.tag >= ?"); params.append(start.isoformat())
    if end:
        cond.append("b.tag <= ?"); params.append(end.isoformat())
    if project_only:
        cond.append("b.project_id IS NOT NULL")
    where = ("WHERE " + " AND ".join(cond)) if cond else ""
    df = _df(f"""SELECT b.*, k.name FROM bookings b
                 JOIN consultants k ON k.id=b.consultant_id {where}""", params)
    df["tag"] = pd.to_datetime(df["tag"]).dt.date
    return df


def recent_changes(n: int = 15) -> pd.DataFrame:
    return _df("""SELECT b.updated_at AS zeitpunkt, b.updated_by AS von, k.name AS berater,
                         b.tag, b.art, c.name AS kunde
                  FROM bookings b JOIN consultants k ON k.id=b.consultant_id
                  LEFT JOIN projects p ON p.id=b.project_id
                  LEFT JOIN clients c ON c.id=p.client_id
                  ORDER BY b.updated_at DESC NULLS LAST LIMIT ?""", (n,))


# ---------------------------------------------------------------- Schreiben: Buchungen
def write_cells(changes: list[tuple[int, dt.date, str | None, int | None]], user: str) -> int:
    """changes: (consultant_id, tag, art | None, project_id | None). art=None löscht die Zelle.
    Zellgenaues Upsert: parallele Änderungen anderer Zellen bleiben unberührt."""
    ts = _now()
    dels = [(int(c), t.isoformat()) for c, t, a, _ in changes if a is None]
    ups = [(int(c), t.isoformat(), a, None if p is None else int(p), user, ts)
           for c, t, a, p in changes if a is not None]
    with connect() as con:
        con.executemany("DELETE FROM bookings WHERE consultant_id=? AND tag=?", dels)
        con.executemany(
            """INSERT INTO bookings(consultant_id,tag,art,project_id,updated_by,updated_at)
               VALUES(?,?,?,?,?,?)
               ON CONFLICT(consultant_id,tag) DO UPDATE SET
                 art=excluded.art, project_id=excluded.project_id,
                 updated_by=excluded.updated_by, updated_at=excluded.updated_at""", ups)
    return len(changes)


def bulk_book(consultant_ids, days, art, project_id, user, overwrite=True) -> int:
    changes = []
    existing = set()
    if not overwrite and days:
        b = bookings(min(days), max(days))
        existing = set(zip(b["consultant_id"], b["tag"]))
    for cid in consultant_ids:
        for d in days:
            if overwrite or (cid, d) not in existing:
                changes.append((int(cid), d, art, project_id))
    return write_cells(changes, user)


def clear_range(consultant_ids, start: dt.date, end: dt.date) -> int:
    with connect() as con:
        n = 0
        for c in consultant_ids:
            n += con.execute("DELETE FROM bookings WHERE consultant_id=? AND tag BETWEEN ? AND ?",
                             (int(c), start.isoformat(), end.isoformat())).rowcount
        return n


# ---------------------------------------------------------------- Kundenerkennung & Logos
_RECHTSFORMEN = r"\b(gmbh|ag|se|kg|kgaa|co|mbh|holding|group|gruppe|international|deutschland)\b"
_UML = str.maketrans({"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"})


def _norm(s: str) -> str:
    s = (s or "").lower().translate(_UML)
    s = re.sub(_RECHTSFORMEN, " ", s)
    return re.sub(r"[^a-z0-9]", "", s)


def match_client(name: str, cutoff: float = 0.8):
    """Erkennt bestehende Kunden trotz Tippfehlern, Rechtsform oder Alias.
    Rückgabe: Zeile (pd.Series) oder None."""
    df = clients(active_only=False)
    n = _norm(name)
    if not n or df.empty:
        return None
    keys: dict[str, int] = {}
    for r in df.itertuples():
        for k in [r.name] + [a for a in (r.aliases or "").split(",") if a.strip()]:
            keys[_norm(k)] = r.id
    hit = keys.get(n)
    if hit is None and len(n) >= 4:
        hit = next((cid for k, cid in keys.items() if len(k) >= 4 and (n in k or k in n)), None)
    if hit is None:
        m = difflib.get_close_matches(n, list(keys), n=1, cutoff=cutoff)
        hit = keys[m[0]] if m else None
    return None if hit is None else df[df["id"] == hit].iloc[0]


def guess_domain(name: str) -> str:
    return f"{_norm(name)}.de" if _norm(name) else ""


def initials_svg(name: str, bg: str = "#6688BB") -> str:
    words = re.findall(r"[A-Za-zÄÖÜäöü0-9]+", name or "?")
    ini = "".join(w[0] for w in words[:2]).upper() or "?"
    svg = (f"<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'>"
           f"<rect width='64' height='64' rx='12' fill='{bg}'/>"
           f"<text x='50%' y='54%' dominant-baseline='middle' text-anchor='middle' "
           f"font-family='Calibri,Arial' font-size='26' font-weight='700' fill='#fff'>{ini}</text></svg>")
    return "data:image/svg+xml;base64," + base64.b64encode(svg.encode()).decode()


def logo_src(name: str, domain: str | None, logo: str | None, token: str | None = None) -> str:
    """Priorität: hochgeladenes Logo > logo.dev (Token) > Favicon-Dienst > Initialen."""
    if isinstance(logo, str) and logo:
        return logo
    if isinstance(domain, str) and domain.strip():
        d = domain.strip().replace("https://", "").replace("http://", "").strip("/")
        if token:
            return f"https://img.logo.dev/{d}?token={token}&size=64&format=png"
        return f"https://www.google.com/s2/favicons?domain={d}&sz=64"
    return initials_svg(name)


def create_client(name: str, domain: str | None = None, aliases: str = "") -> int:
    with connect() as con:
        return con.insert_id("INSERT INTO clients(name, domain, aliases) VALUES(?,?,?)",
                             (name.strip(), (domain or guess_domain(name)).strip(), (aliases or "").strip()))


def ensure_project(client_id: int, name: str) -> int:
    name = (name or "Projekt").strip()
    with connect() as con:
        row = con.execute("SELECT id FROM projects WHERE client_id=? AND name=?", (client_id, name)).fetchone()
        if row:
            return row["id"]
        return con.insert_id("INSERT INTO projects(client_id, name) VALUES(?,?)", (client_id, name))


def create_consultant(name: str, vollname: str = "", rolle: str = "") -> tuple[int, bool]:
    """Legt einen Mitarbeiter an oder reaktiviert ihn. Rückgabe: (id, neu_angelegt)."""
    name = name.strip()
    with connect() as con:
        row = con.execute("SELECT id FROM consultants WHERE LOWER(name)=LOWER(?)", (name,)).fetchone()
        if row:
            con.execute("UPDATE consultants SET aktiv=1, vollname=COALESCE(NULLIF(?, ''), vollname), "
                        "rolle=COALESCE(NULLIF(?, ''), rolle) WHERE id=?", (vollname, rolle, row["id"]))
            return row["id"], False
        nxt = con.execute("SELECT COALESCE(MAX(sort), -1) + 1 AS n FROM consultants").fetchone()["n"]
        return con.insert_id("INSERT INTO consultants(name, vollname, rolle, sort) VALUES(?,?,?,?)",
                             (name, vollname or None, rolle or None, nxt)), True


def update_project_meta(project_id: int, budget: float | None, start: dt.date | None, ende: dt.date | None) -> None:
    with connect() as con:
        con.execute("UPDATE projects SET budget_tage=COALESCE(?, budget_tage), start=COALESCE(?, start), "
                    "ende=COALESCE(?, ende), aktiv=1 WHERE id=?",
                    (budget, start.isoformat() if start else None, ende.isoformat() if ende else None, project_id))


def reset_planning() -> None:
    """Löscht alle Buchungen, Projekte und Kunden. Das Team bleibt erhalten."""
    with connect() as con:
        con.execute("DELETE FROM bookings")
        con.execute("DELETE FROM projects")
        con.execute("DELETE FROM clients")


def set_logo(client_id: int, data_uri: str | None) -> None:
    with connect() as con:
        con.execute("UPDATE clients SET logo=? WHERE id=?", (data_uri, client_id))


# ---------------------------------------------------------------- Stammdaten speichern
def _isnew(v) -> bool:
    return v is None or (isinstance(v, float) and pd.isna(v))


def save_table(table: str, cols: list[str], edited: pd.DataFrame, original: pd.DataFrame) -> None:
    """Upsert geänderter Zeilen, entfernte Zeilen werden deaktiviert (Soft Delete)."""
    def val(v):
        if isinstance(v, (dt.date, dt.datetime)):
            return v.isoformat()[:10]
        if v is None or (isinstance(v, float) and pd.isna(v)) or v is pd.NaT:
            return None
        return v.item() if hasattr(v, "item") else v

    with connect() as con:
        for _, r in edited.iterrows():
            values = [val(r.get(c)) for c in cols]
            if _isnew(r.get("id")):
                if not values[0]:
                    continue
                con.execute(f"INSERT INTO {table}({','.join(cols)}) VALUES({','.join('?' * len(cols))})", values)
            else:
                sets = ",".join(f"{c}=?" for c in cols)
                con.execute(f"UPDATE {table} SET {sets} WHERE id=?", values + [int(r['id'])])
        removed = set(original["id"].dropna().astype(int)) - set(edited["id"].dropna().astype(int))
        for rid in removed:
            con.execute(f"UPDATE {table} SET aktiv=0 WHERE id=?", (rid,))


# ---------------------------------------------------------------- Demo-Daten
def seed_demo(team_kuerzel: list[str] | None = None) -> None:
    today = dt.date.today()
    team = [("Max", "", "Senior Consultant"), ("Anna", "", "Projektleiterin"),
            ("Ben", "", "Consultant"), ("Clara", "", "Senior Consultant"),
            ("David", "", "Consultant"), ("Eva", "", "Projektleiterin"),
            ("Felix", "", "Consultant"), ("Hannah", "", "Senior Consultant"),
            ("Jonas", "", "Consultant"), ("Lena", "", "Consultant")]
    # Fiktive Demo-Kunden (keine echten Mandanten)
    kunden = [("Alpenwerk Maschinenbau", "", "Alpenwerk", "S&OP Einführung"),
              ("Isartal Chemie", "", "ITC", "Footprint Analyse"),
              ("Brennerhof Möbel", "", "BHM", "Baukasten Portfolio"),
              ("Donaumetall", "", "DM", "Szenarien Produktion"),
              ("Nordstern Logistik", "", "", "Lageroptimierung"),
              ("Bergmann Medizintechnik", "", "BMT", "OpEx Programm"),
              ("Kessler Antriebe", "", "", "Supply Chain")]
    if team_kuerzel:
        team = [(k, "", "") for k in team_kuerzel]
    rng = random.Random(42)
    with connect() as con:
        for i, (n, v, r) in enumerate(team):
            con.execute("INSERT INTO consultants(name,vollname,rolle,sort) VALUES(?,?,?,?)",
                        (n, v or None, r or None, i))
        pids = []
        for name, dom, ali, proj in kunden:
            cid = con.insert_id("INSERT INTO clients(name,domain,aliases) VALUES(?,?,?)", (name, dom, ali))
            pids.append(con.insert_id("INSERT INTO projects(client_id,name) VALUES(?,?)", (cid, proj)))
        cons = [r["id"] for r in con.execute("SELECT id FROM consultants ORDER BY id").fetchall()]

    start = logic.monday(today) - dt.timedelta(weeks=8)
    end = logic.month_end(today, 5)
    days = logic.workdays(start, end)
    changes = []
    for cid in cons:
        cur = start
        while cur < end:
            # Pipeline wird nach hinten dünner: realistische Kapazitätslücke ab ca. 8 Wochen
            if cur > today + dt.timedelta(weeks=8) and rng.random() < 0.45:
                cur += dt.timedelta(weeks=rng.randint(2, 5))
                continue
            pid = rng.choice(pids)
            stop = cur + dt.timedelta(weeks=rng.randint(4, 10))
            for d in (x for x in days if cur <= x < stop):
                if d.weekday() <= 3:
                    art = "Vor Ort" if rng.random() > 0.1 else "Remote"
                else:
                    art = rng.choice(["Remote", "Intern", "Remote", "Akquise"])
                changes.append((cid, d, art, pid if art in logic.PROJEKT_ARTEN else None))
            cur = stop
        urlaub = logic.monday(today) + dt.timedelta(weeks=rng.randint(1, 14))
        for d in (x for x in days if urlaub <= x < urlaub + dt.timedelta(days=5)):
            changes.append((cid, d, "Urlaub", None))
    write_cells(changes, "Demo")

    with connect() as con:
        for pid in pids:
            row = con.execute("""SELECT MIN(tag) s, MAX(tag) e, COUNT(*) n FROM bookings
                                 WHERE project_id=?""", (pid,)).fetchone()
            budget = round((row["n"] or 0) * rng.uniform(0.9, 1.3) / 5) * 5
            con.execute("UPDATE projects SET start=?, ende=?, budget_tage=? WHERE id=?",
                        (row["s"], row["e"], budget, pid))
